name: Build & Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTH_TOKEN }}

      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.4'
      
      - name: Install Pollen
        run: raco pkg install --no-docs --auto pollen
          
      - name: Build and Publish Pollen Source Files
        run: > 
          make publish

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: build
